Resources:
  AlamandaApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: AlamandaApi::AlamandaApi.LambdaEntryPoint::FunctionHandlerAsync
      Runtime: dotnet8
      MemorySize: 256
      Timeout: 30
      Events:
        Api:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
